### ISSUE TITLE
Can read ibm float but not write it

### ISSUE THREAD

**Issue by wassname** [rob-smallshire/segpy#11]
This library is very useful. One problem I have run into is that it can read ibm float (by converting to ieee) but not write it. Different way to deal with this would be:
1. Write to ieee, by changing cformat and also the reel_header
2. Implementing ieee2ibm and writing this way

The work around I am using is adding:

        # Write Data. Cannot write ibm float so use ieee instead.
        if ctype == 'ibm':
            ctype='f'

To line 398 in segypy.py as a dirty hack as I haven't managed to work out how to correctly change the reel header.

**Comment by rob-smallshire** [comment]
Thanks for your comment.

The implementation of write_segy() which Segpy inherited from the legacy SegyPy library is broken; it accepts a (reel) header value, but then ignores it.  In fact, there are a multitude of similar niggles I have with the old SegyPy code, so I've rewritten the whole thing with a view to having a much more flexible and correct toolkit for reading and writing SEG Y.  As such, I'm directing my energies towards releasing that, rather than maintaining the old code. 

The forthcoming Segpy version 2 has full support for writing IBM float values.  If you want to try to use it you can check out the 'rewrite' branch from here on GitHub.  Convenience classes for writing SEG Y are not yet in place, but most of the lower-level toolkit functions for writing SEG Y are there.

I'd like to make an initial release of Segpy 2.0 before the end of this month (January 2015), so you shouldn't have long to wait.

**Comment by wassname** [comment]
That's good to know, I'll have a look at the new library!

I get a kick out of seeing people use what I've made, so I'll tell you what I'm using it for. I'm in Australia and a co-worker and I are doing a lot of seismic loading and use this at least once a week to 1) Analyse segy files and produce XML output's for Petrel's 2D toolbox 2) Modify headers in batch in ways that are too tedious in Seisee.

Implementing writing support sounds like a nice challenge, I had a look and quickly decided I was to tired for it.

**Comment by wassname** [comment]
Hi Rob, I had a look at Segpy 2.0 and it looks nice, I see you've implemented ieee2ibm already. If you want feedback or test data let me know. From having a try of it I my biggest suggestion would be be 1) make it a module with an __init__.py and 2) expand the tests to include reading and writing.

**Comment by rob-smallshire** [comment]
@wassname Do you have any SEG Y files with extended textual headers I could use for testing reading and writing of those?  That's something I'm missing from my (small) corpus of examples I use for testing.

**Comment by wassname** [comment]
I haven't come across any and don't have the tools to generate them sorry, but I'll keep an eye out and something might pop up.

**Comment by wassname** [comment]
Hey Rob, had another look at segpy/rewrite and it's looking pretty fantastic. Great recent commits.
